import next from '@pharmacy/eslint-config/next';

/**
 * Next.js app ESLint config — the shared flat config plus app-local ignores.
 * `next-env.d.ts` is generated by Next (it emits a triple-slash path reference
 * that our base rules reject), so it is excluded from linting.
 */
export default [{ ignores: ['next-env.d.ts'] }, ...next];
